// docutils.cpp : Entry point demonstrating tree-sitter-latex parser integration.

#include <iostream>
#include <string>
#include <tree_sitter/api.h>

// External declaration for the LaTeX language symbol generated by tree-sitter-latex
extern "C" const TSLanguage* tree_sitter_latex();

// Helper function to recursively print the AST nodes
void print_node(TSNode node, const std::string& source, int depth = 0) {
    if (ts_node_is_null(node)) return;

    std::string indent(depth * 2, ' ');
    const char* type = ts_node_type(node);
    bool is_named = ts_node_is_named(node);

    uint32_t start_byte = ts_node_start_byte(node);
    uint32_t end_byte = ts_node_end_byte(node);
    uint32_t child_count = ts_node_child_count(node);

    std::cout << indent << (is_named ? "[Named] " : "[Anonymous] ") << type;

    // For leaf nodes (no children), print the extracted source text snippet
    if (child_count == 0 && end_byte > start_byte && end_byte <= source.length()) {
        std::string text = source.substr(start_byte, end_byte - start_byte);
        // Sanitize newlines for cleaner single-line output
        size_t pos = 0;
        while ((pos = text.find('\n', pos)) != std::string::npos) {
            text.replace(pos, 1, "\\n");
            pos += 2;
        }
        std::cout << " -> \"" << text << "\"";
    }
    std::cout << "\n";

    // Recurse child nodes
    for (uint32_t i = 0; i < child_count; ++i) {
        TSNode child = ts_node_child(node, i);
        print_node(child, source, depth + 1);
    }
}

int main() {
    std::cout << "=== Tree-Sitter LaTeX Integration Demo ===\n\n";

    // 1. Create a new Tree-Sitter parser instance
    TSParser* parser = ts_parser_new();
    if (!parser) {
        std::cerr << "Failed to create tree-sitter parser.\n";
        return 1;
    }

    // 2. Set the parser language to tree-sitter-latex
    const TSLanguage* latex_lang = tree_sitter_latex();
    if (!latex_lang) {
        std::cerr << "Failed to load tree-sitter LaTeX grammar.\n";
        ts_parser_delete(parser);
        return 1;
    }
    ts_parser_set_language(parser, latex_lang);

    // 3. Define sample LaTeX source text
    std::string latex_source =
        "\\documentclass{article}\n"
        "\\begin{document}\n"
        "\\section{Introduction}\n"
        "Hello Tree-sitter LaTeX! Mass-energy relation: $E = mc^2$.\n"
        "\\end{document}\n";

    std::cout << "Source Code:\n" << latex_source << "\n";

    // 4. Parse the LaTeX source code
    TSTree* tree = ts_parser_parse_string(
        parser,
        nullptr,
        latex_source.c_str(),
        static_cast<uint32_t>(latex_source.length())
    );

    if (!tree) {
        std::cerr << "Failed to parse LaTeX source.\n";
        ts_parser_delete(parser);
        return 1;
    }

    // 5. Retrieve root AST node
    TSNode root_node = ts_tree_root_node(tree);

    // 6. Print S-Expression string representation of the AST
    std::cout << "--- AST S-Expression ---\n";
    char* s_expr = ts_node_string(root_node);
    if (s_expr) {
        std::cout << s_expr << "\n\n";
        free(s_expr); // Free memory allocated by tree-sitter for s_expr
    }

    // 7. Perform structural tree traversal and print nodes
    std::cout << "--- Structural AST Traversal ---\n";
    print_node(root_node, latex_source);

    // 8. Clean up resources
    ts_tree_delete(tree);
    ts_parser_delete(parser);

    std::cout << "\nSuccessfully completed LaTeX AST parsing demo!\n";
    return 0;
}
